### ISSUE TITLE
IOError Tracebacks

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/softwareupdater#31]
During the development of my log analysis program I found that all of the beta nodes were logging some exception tracebacks.  This specific category of log entries (IOErrors) has been seen about 80 times on all beta nodes since July 23rd, which was when the beta nodes were reinstalled. The nodes are using version 0.1r-beta-r3519.

The general IOError's seem to fall into two sub-categories.  One being a 'No such file or directory' error and the rest being various socket errors, both seen about 40 times.  Below I have attached one of each of the log entries in question:

1280576739.02:PID-31937:Traceback (most recent call last):     
        File "softwareupdater.py", line 830, in <module>        
        File "softwareupdater.py", line 753, in main    
        File "softwareupdater.py", line 251, in do_rsync        
        File "/home/uw_seattle/seattle/seattle_repy/emulfile.py", line 144, in emulated_open    
        File "/home/uw_seattle/seattle/seattle_repy/emulfile.py", line 316, in __init__       
IOError: [2](Errno) No such file or directory: '/tmp/tmpzFAASg/metainfo'

1280590621.56:PID-9848:Traceback (most recent call last):	  
	File "softwareupdater.py", line 167, in safe_download	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/urllib.py", line 89, in urlretrieve	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/urllib.py", line 222, in retrieve	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/urllib.py", line 190, in open	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/urllib.py", line 325, in open_http	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/httplib.py", line 856, in endheaders	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/httplib.py", line 728, in _send_output	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/httplib.py", line 695, in send	  
	File "/vservers/.vref/onelab-f8-i386/usr/lib/python2.5/httplib.py", line 679, in connect	
IOError: [socket error](Errno) timed out

It seems that the missing directory error typically occurs right after a socket time out error.

Among the socket errors a majority of them are entries that indicate a time out, but a few others had  "IOError: [socket error](Errno) (-3, 'Temporary failure in name resolution')" and "IOError: [socket error](Errno) (113, 'No route to host')" as their last line but are also from softwareupdater.py and from safe_download on line 167.

The IP addresses of the nodes in question (ie. all beta nodes) are:
192.26.179.68, 210.123.39.168, 192.33.90.196, 140.192.249.203, 133.9.81.166, 139.80.206.132, 200.0.206.203, 137.148.16.10, 128.112.139.28, 140.109.17.180 and 131.193.34.21

**Comment by aaaaalbert** [comment]
I haven't seen this behavior on nodes running a current version of Seattle. Given the age of the issue and the changes to the codebase since, I'm closing this.
